name:                 memoization
version:              0.1.0.0
visibility:           public
id:                   memoization-0.1.0.0-G2fTMDa2CP38evbHGpvH8L
key:                  memoization-0.1.0.0-G2fTMDa2CP38evbHGpvH8L
license:              BSD-3-Clause
copyright:            2025 Noric Couderc
maintainer:           noric.couderc@cs.lth.se
author:               Noric Couderc
homepage:             https://github.com/githubuser/memoization#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/memoization#readme>

abi:                  9c265269a40ec3415e05d349135470f5
exposed:              True
exposed-modules:      Memoization MonadicMemoization StringAlignment
hidden-modules:       Paths_memoization
import-dirs:
    "/Users/simongustafsson/Desktop/Bachelors in Mathematics/EDAN40/project_2/.stack-work/install/aarch64-osx/a47b28e08280c1d53b2405b76b6efedba2ec2fa22ccade886cc50b89201311fd/9.4.8/lib/aarch64-osx-ghc-9.4.8/memoization-0.1.0.0-G2fTMDa2CP38evbHGpvH8L"

library-dirs:
    "/Users/simongustafsson/Desktop/Bachelors in Mathematics/EDAN40/project_2/.stack-work/install/aarch64-osx/a47b28e08280c1d53b2405b76b6efedba2ec2fa22ccade886cc50b89201311fd/9.4.8/lib/aarch64-osx-ghc-9.4.8/memoization-0.1.0.0-G2fTMDa2CP38evbHGpvH8L"

library-dirs-static:
    "/Users/simongustafsson/Desktop/Bachelors in Mathematics/EDAN40/project_2/.stack-work/install/aarch64-osx/a47b28e08280c1d53b2405b76b6efedba2ec2fa22ccade886cc50b89201311fd/9.4.8/lib/aarch64-osx-ghc-9.4.8/memoization-0.1.0.0-G2fTMDa2CP38evbHGpvH8L"

dynamic-library-dirs:
    "/Users/simongustafsson/Desktop/Bachelors in Mathematics/EDAN40/project_2/.stack-work/install/aarch64-osx/a47b28e08280c1d53b2405b76b6efedba2ec2fa22ccade886cc50b89201311fd/9.4.8/lib/aarch64-osx-ghc-9.4.8"

data-dir:
    "/Users/simongustafsson/Desktop/Bachelors in Mathematics/EDAN40/project_2/.stack-work/install/aarch64-osx/a47b28e08280c1d53b2405b76b6efedba2ec2fa22ccade886cc50b89201311fd/9.4.8/share/aarch64-osx-ghc-9.4.8/memoization-0.1.0.0"

hs-libraries:         HSmemoization-0.1.0.0-G2fTMDa2CP38evbHGpvH8L
depends:
    base-4.17.2.1 containers-0.6.7 mtl-2.2.2
    random-1.2.1.1-5A411GLqDA5B9LXzgGkW7g

haddock-interfaces:
    "/Users/simongustafsson/Desktop/Bachelors in Mathematics/EDAN40/project_2/.stack-work/install/aarch64-osx/a47b28e08280c1d53b2405b76b6efedba2ec2fa22ccade886cc50b89201311fd/9.4.8/doc/memoization-0.1.0.0/memoization.haddock"

haddock-html:
    "/Users/simongustafsson/Desktop/Bachelors in Mathematics/EDAN40/project_2/.stack-work/install/aarch64-osx/a47b28e08280c1d53b2405b76b6efedba2ec2fa22ccade886cc50b89201311fd/9.4.8/doc/memoization-0.1.0.0"
